language: node_js
node_js: '12'
sudo: required
if: tag IS present OR branch  = master
services:
  - docker
before_install:
  - docker build -t malcoded-backend .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=malcoded/backend
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_TAG ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT latest
  - docker push $REPO
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
