version: '3'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile  

    
    volumes:
      - ..:/workspace  

    command: sleep infinity  

  mongo:
    image: mongo:3.6
    